export const st: any = {
  panel: { position: 'fixed', background: '#1e1e2e', color: '#cdd6f4', borderRadius: '10px', fontFamily: 'ui-monospace, monospace', fontSize: '12px', boxShadow: '0 8px 24px rgba(0,0,0,.4)', zIndex: 2147483647, overflow: 'hidden', display: 'flex', flexDirection: 'column', userSelect: 'none' },
  header: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '8px 10px', background: '#313244', cursor: 'move', flex: '0 0 auto' },
  host: { opacity: 0.5, fontWeight: 'normal', marginLeft: 6 },
  toolbar: { display: 'flex', gap: 6, alignItems: 'center', padding: '6px 8px', borderBottom: '1px solid #313244', flex: '0 0 auto' },
  resume: { marginLeft: 'auto', fontSize: 11, color: '#f9e2af' },
  controls: { display: 'flex', flexWrap: 'wrap', gap: 6, alignItems: 'center', padding: '6px 8px', borderBottom: '1px solid #313244', flex: '0 0 auto', fontSize: 11 },
  ctrlLabel: { display: 'inline-flex', alignItems: 'center', gap: 3, color: '#a6adc8' },
  numIn: { width: 46, background: '#181825', color: '#cdd6f4', border: '1px solid #45475a', borderRadius: 4, fontSize: 11, padding: '1px 3px' },
  sel: { background: '#181825', color: '#cdd6f4', border: '1px solid #45475a', borderRadius: 4, fontSize: 11 },
  stopBtn: { background: '#f38ba8', border: 'none', color: '#11111b', borderRadius: 5, padding: '3px 10px', cursor: 'pointer', fontWeight: 'bold', fontSize: 11 },
  ioBtn: { background: 'none', border: '1px solid #45475a', color: '#a6adc8', borderRadius: 5, padding: '3px 6px', cursor: 'pointer', fontSize: 11 },
  resetBtn: { background: 'none', border: '1px solid #45475a', color: '#f9e2af', borderRadius: 5, padding: '3px 8px', cursor: 'pointer', fontSize: 11 },
  chk: { width: 12, height: 12, flex: '0 0 auto', margin: 0 },
  cellRowOff: { opacity: 0.4 },
  main: { display: 'flex', flexDirection: 'column', flex: '1 1 auto', minHeight: 0 },
  topArea: { display: 'flex', flex: '1 1 auto', minHeight: 0 },
  list: { borderRight: '1px solid #313244', overflowY: 'auto', flex: '0 0 auto' },
  vsplit: { width: 5, flex: '0 0 auto', cursor: 'col-resize', background: '#313244' },
  hsplit: { height: 5, flex: '0 0 auto', cursor: 'row-resize', background: '#313244' },
  outputWrap: { display: 'flex', flexDirection: 'column', flex: '0 0 auto', minHeight: 0 },
  outputHead: { padding: '3px 8px', fontSize: 10, letterSpacing: 0.5, textTransform: 'uppercase', color: '#89b4fa', background: '#181825', flex: '0 0 auto' },
  empty: { padding: 10, opacity: 0.5 },
  cellRow: { display: 'flex', alignItems: 'center', gap: 6, padding: '6px 8px', cursor: 'pointer', borderBottom: '1px solid #26263a' },
  cellRowActive: { background: '#313244' },
  cellRowDrag: { borderTop: '2px solid #89b4fa' },
  grip: { cursor: 'grab', opacity: 0.4, flex: '0 0 auto', fontSize: 12, lineHeight: 1 },
  cellName: { flex: 1, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' },
  dot: (s: string) => ({ width: 8, height: 8, borderRadius: '50%', flex: '0 0 auto', background: s === 'ok' ? '#a6e3a1' : s === 'error' ? '#f38ba8' : s === 'running' ? '#f9e2af' : '#585b70' }),
  runBtn: { background: 'none', border: 'none', color: '#89b4fa', cursor: 'pointer', fontSize: 12 },
  editorPane: { flex: 1, display: 'flex', flexDirection: 'column', minWidth: 0 },
  editorHead: { display: 'flex', justifyContent: 'space-between', padding: '6px 8px', borderBottom: '1px solid #313244' },
  editorTitle: { color: '#89b4fa' },
  textarea: { flex: '1 1 auto', resize: 'none', border: 'none', outline: 'none', background: '#181825', color: '#cdd6f4', fontFamily: 'ui-monospace, monospace', fontSize: 12, padding: 8, userSelect: 'text' },
  runRow: { padding: '6px 8px', borderTop: '1px solid #313244', flex: '0 0 auto' },
  output: { margin: 0, padding: 8, flex: '1 1 auto', overflow: 'auto', background: '#11111b', whiteSpace: 'pre-wrap', wordBreak: 'break-word', userSelect: 'text' },
  iconBtn: { background: 'none', border: 'none', color: '#cdd6f4', cursor: 'pointer' },
  smallBtn: { background: '#45475a', border: 'none', color: '#cdd6f4', borderRadius: 5, padding: '3px 8px', cursor: 'pointer', fontSize: 11 },
  primaryBtn: { background: '#89b4fa', border: 'none', color: '#11111b', borderRadius: 5, padding: '4px 10px', cursor: 'pointer', fontWeight: 'bold' },
  linkBtn: { background: 'none', border: 'none', color: '#f38ba8', cursor: 'pointer', fontSize: 11, marginLeft: 6 },
  mini: { position: 'fixed', top: 20, right: 20, zIndex: 2147483647, border: 'none', borderRadius: '50%', width: 38, height: 38, cursor: 'pointer', background: '#313244', color: '#fff', fontSize: 16 },
  resizeHandle: { position: 'absolute', right: 0, bottom: 0, width: 14, height: 14, cursor: 'nwse-resize', background: 'linear-gradient(135deg, transparent 50%, #89b4fa 50%)' },
};
